# Generated by Django 5.1.1 on 2024-11-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblogapp', '0002_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
