# Generated by Django 5.1.1 on 2024-11-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblogapp', '0003_alter_post_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
